siteName: Surjyadip Sen
description: Full Stack Developer specializing in scalable real-time data analytics and AI-driven automation.
socialLinks:
  - platform: Github
    url: https://github.com/XotEmBotZ
  - platform: LinkedIn
    url: https://www.linkedin.com/in/surjyadip-sen
copyright: "© 2026 Surjyadip Sen"
